spring:
  webflux:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: Content-Type, Authorization
  application:
    name: security-service
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jwtsecurity
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    sql: info
    root: info
server:
  port: 8200


